CREATE TABLE cache (
    id SERIAL PRIMARY KEY,
    type varchar(100),
    query text NOT NULL,
    data jsonb,
    created timestamp DEFAULT NOW()
);
COMMENT ON TABLE cache IS 'Stores resource-intensive operations (like http requests) so they can be loaded quickly.';
COMMENT ON COLUMN cache.type IS 'The type of data being stored. This is just an arbitrary string to group entries.';
COMMENT ON COLUMN cache.query IS 'The query that was used to generate the data. Together with type, this is how the data is retrieved.';
COMMENT ON COLUMN cache.data IS 'The data that was generated by the query.';
COMMENT ON COLUMN cache.created IS 'The timestamp when this cache entry was created.';
