x-variables:
  main-image: &main-image localhost/local-dev/open-access-fund:local-dev
services:
  admin-app:
    image: *main-image
    env_file:
      - .env
    environment:
      ADMIN_APP_ENV: 'dev'
      SUBMISSION_FORM_URL: 'http://localhost:3001'
      GOOGLE_APPLICATION_CREDENTIALS: /etc/gc-service-account.json
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
    volumes:
      - ../../../services:/services
      - /services/node_modules
      - ../../../secrets/gc-reader-key.json:/etc/gc-service-account.json
    depends_on:
      - db
    ports:
      - ${ADMIN_APP_HOST_PORT:-3000}:${ADMIN_APP_CONTAINER_PORT:-3000}
  submission-dev:
    image: *main-image
    env_file:
      - .env
    volumes:
      - ../../../services/client/submission-dev:/services/client/submission-dev
    ports:
      - ${SUBMISSION_DEV_HOST_PORT:-3001}:8080
    command: ["npm", "run", "start-submission-dev"]
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: localhost
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../../../services/pg/schema:/docker-entrypoint-initdb.d
  adminer:
    image: adminer:5
    ports:
      - ${ADMINER_HOST_PORT:-8080}:8080
  migration-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: localhost
      MYSQL_DATABASE: bigsys
      MYSQL_USER: mysql
      MYSQL_PASSWORD: localhost
    volumes:
      - migration-db-data:/var/lib/mysql
      - ../../../services/migration/data:/docker-entrypoint-initdb.d
  migration:
    image: *main-image
    environment:
      MYSQL_DATABASE: bigsys
      MYSQL_USER: mysql
      MYSQL_PASSWORD: localhost
      MYSQL_HOST: migration-db
      MYSQL_PORT: 3306
      PGUSER: 'postgres'
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'localhost'
      PGPORT: 5432
    depends_on:
      - migration-db
      - db
    volumes:
      - ../../../services:/services
      - /services/node_modules
volumes:
  db-data:
  migration-db-data:
